# Generated by Django 4.1.1 on 2022-10-01 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud_app', '0002_task_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='category',
            field=models.CharField(choices=[('Out Door', 'Out Door'), ('In Door', 'In Door')], max_length=35),
        ),
    ]
